version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "monthly"
