name: Get Latest Release Version
on: [push, repository_dispatch]

permissions:
  contents: read

jobs:
  get-latest-release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the latest release tag
        id: get_release
        run: |
          LATEST_TAG=$(gh release view --json tagName -q ".tagName")
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Print the latest tag
        run: echo "The latest release tag is $LATEST_TAG"

      - name: Configure Git
        run: |
          git config --global user.name "nefarious-developer[bot]"
          git config --global user.email "nefarious-developer[bot]@noreply.github.com"

      - name: Clone the target repository
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/The-Nefarious-Developer/zjoule-website.git target-repo
          cd target-repo

      - name: Create a new branch
        run: |
          git checkout -b update-to-$LATEST_TAG

      - name: Run the script to update the website
        run: |
          ./update-website.sh $LATEST_TAG

      - name: Commit the changes
        run: |
          git add .
          git commit -m "feat: update to $LATEST_TAG"
      
      - name: Push the changes
        run: |
          git push origin update-to-$LATEST_TAG